{% set pkg_name = "tinyxml2" %}
{% set git_url = "https://github.com/leethomason/tinyxml2.git" %}
{% set git_rev = "11.0.0" %}

package:
  name: "{{ pkg_name }}"
  version: "{{ git_rev }}"

source:
  git_url: "{{ git_url }}"
  git_rev: "{{ git_rev }}"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libtinyxml2.dylib && echo "libtinyxml2.dylib found" || echo "libtinyxml2.dylib not found"

about:
  home: https://github.com/leethomason/tinyxml2
  summary: "XML parser"
